### ISSUE TITLE
"Game not found!" in console

### ISSUE THREAD

**Issue by ghost** [C0HERENCE/LiteSDKGenerator#3]

**Comment by C0HERENCE** [comment]
Run the game from explorer, at "...\PUBGLite\Client\PUBGLite.exe"
Your visual studio should run as administrator
Add breaks in https://github.com/C0HERENCE/LiteSDKGenerator/blob/407f6a8aef2a14817edfc3bc7c5353edf2ba36ad/LiteSDKGenerator/Memory.cpp#L3

to see what happened

**Comment by C0HERENCE** [comment]
There are 7 "return false;" statements in https://github.com/C0HERENCE/LiteSDKGenerator/blob/407f6a8aef2a14817edfc3bc7c5353edf2ba36ad/LiteSDKGenerator/Memory.cpp#L3, 
Check it yourself

**Comment by cristlxrd** [comment]
ok thx
