### ISSUE TITLE
doesn't find the game :D

### ISSUE THREAD

**Issue by Vaseliinikives** [C0HERENCE/LiteSDKGenerator#4]
game is open but it ain't finding it.
https://i.imgur.com/tHhAxSq.png

**Comment by Vaseliinikives** [comment]
i was able to find the fix for that, but it ain't finding offsets.
offsets here should be up to date
![image](https://user-images.githubusercontent.com/45107100/72655450-54963400-399d-11ea-8376-eaaa31759966.png)

**Comment by C0HERENCE** [comment]
> game is open but it ain't finding it.
> https://i.imgur.com/tHhAxSq.png

Have you fixed it? Can you tell me what changes you made.

**Comment by C0HERENCE** [comment]
> i was able to find the fix for that, but it ain't finding offsets.
> offsets here should be up to date
> ![image](https://user-images.githubusercontent.com/45107100/72655450-54963400-399d-11ea-8376-eaaa31759966.png)
Did you update decryption functions?
What about Uobject Test Button or SDK export Button

**Comment by Vaseliinikives** [comment]
this is what it gives when clicking uobject test button, and sdk button does not generate anything.
probably wrong decryptions, ill look for new ones tomorrow.
![image](https://user-images.githubusercontent.com/45107100/72658615-10fef280-39bc-11ea-85b3-7e5b3c9538d5.png)

**Comment by Vaseliinikives** [comment]
> > i was able to find the fix for that, but it ain't finding offsets.
> > offsets here should be up to date
> > ![image](https://user-images.githubusercontent.com/45107100/72655450-54963400-399d-11ea-8376-eaaa31759966.png)
> > Did you update decryption functions?
> > What about Uobject Test Button or SDK export Button

do you have sigs for those offsets and decryptions, i don't have any of those. or can you update them :D

**Comment by Vaseliinikives** [comment]
?

**Comment by reddude256** [comment]
Vaseliinikives can you make your PUBG lite cheat open source? So we can update it ourselfs

**Comment by Vaseliinikives** [comment]
facts :DD
![image](https://user-images.githubusercontent.com/45107100/72866851-736e3080-3ce5-11ea-8b0a-86e9538934f3.png)

**Comment by C0HERENCE** [comment]
> facts :DD
> ![image](https://user-images.githubusercontent.com/45107100/72866851-736e3080-3ce5-11ea-8b0a-86e9538934f3.png)

facts:
1. You must run the game with out anti-cheat so this generator can do ReadProcessMemory()
2. I won't provide any sigs or decryption.
3. Learn how to use the original sdk generator by @KN4CK3R.
