### ISSUE TITLE
Doesn't generate anything.

### ISSUE THREAD

**Issue by vxnd** [C0HERENCE/LiteSDKGenerator#5]
Game is started without anticheat, it just freezes when trying to export sdk, or export useful.
Also UObject test gives NULL values.
Offsets and decryptions should be up to date, they are from you.
![image](https://user-images.githubusercontent.com/60287434/73119443-7d549580-3f6a-11ea-9038-adc806287b61.png)

**Comment by C0HERENCE** [comment]
@Vaseliinikives https://youtu.be/AvgOZhQbv9s
